### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by AXCWG** [Bumer-32/I-Want-To-Control-My-Server#16]
Anyone can connect to the websocket server and send commands. 

<img width="687" alt="Screenshot 2024-11-26 at 11 20 38" src="https://github.com/user-attachments/assets/ab77b303-f82d-4e98-9048-3f8cce6e8f14">

Directly from browser. No authentication or cookie stored.

**Comment by Bumer-32** [comment]
@AXCWG  Is auth enabled in the config? All works fine, messages sends but did not being processed

 ̶I̶ ̶d̶o̶n̶'̶t̶ ̶r̶e̶a̶l̶l̶y̶ ̶u̶n̶d̶e̶r̶s̶t̶a̶n̶d̶ ̶w̶h̶a̶t̶ ̶y̶o̶u̶ ̶w̶a̶n̶t̶e̶d̶ ̶t̶o̶ ̶s̶h̶o̶w̶ ̶i̶n̶ ̶t̶h̶e̶ ̶s̶c̶r̶e̶e̶n̶s̶h̶o̶t̶,̶ ̶h̶o̶w̶ ̶d̶o̶ ̶y̶o̶u̶ ̶w̶a̶n̶t̶ ̶t̶o̶ ̶c̶o̶n̶n̶e̶c̶t̶ ̶t̶o̶ ̶t̶h̶e̶ ̶w̶e̶b̶s̶o̶c̶k̶e̶t̶ ̶v̶i̶a̶ ̶h̶t̶t̶p̶:̶/̶/̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶w̶s̶:̶/̶/̶?̶   ok, did not know that the browser automatically substitutes ws:// instead of http://

**Comment by AXCWG** [comment]
> @AXCWG Is auth enabled in the config? All works fine, messages sends but did not being processed

whoops.
